version: '3'
services:
    memcache:
        image: memcached:1.5

    php-fpm:
        build:
            context: ./php-fpm
        volumes:
            - ../app:/app

            - ./data/php-fpm/logs:/var/log/php-fpm
            - ./php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php-fpm/conf/web.conf:/usr/local/etc/php-fpm.d/web.conf
    nginx:
        image: nginx
        depends_on:
            - php-fpm
        volumes:
            - /app:/app
            - ./data/nginx/logs:/var/log/nginx
            - ./nginx/conf/sites/:/etc/nginx/conf.d
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "127.0.0.1:80:80"
        links:
            - php-fpm

    elasticsearch:
        build:
            context: ./elasticsearch


    mysql:
        image: mysql
        volumes:
            - ./data/mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bank
            MYSQL_USER: bank
            MYSQL_PASSWORD: bank
        ports:
            - "127.0.0.1:3306:3306"
